### ISSUE TITLE
reduce font size for heatmap

### ISSUE THREAD

**Issue by cathalgking** [mildpiggy/DEP2#10]
How can I reduce the font size for the labels above the heatmap showing missing values?

```{r}
plot_missval(se = plate1_norm, 
             column_title = "Proteins with missing values for plate 1 filt",
             column_title_gp=grid::gpar(fontsize=12))
```
<img width="265" alt="Screenshot 2024-06-07 at 10 30 55 AM" src="https://github.com/mildpiggy/DEP2/assets/32261323/3730cac1-5b08-46bc-b129-06f4cd3a4c17">

**Comment by mildpiggy** [comment]
The labels size is set by column_names_gp parameter. We already set `column_names_gp = gpar(fontsize = 16)` in `plot_missval` and we did not reserve this parameter interface. , thus you cannot change it directly.  As an optional method, you can redefine the `plot_missval` function by adding the column_names_gp parameter interface or adjusting the `fontsize` value inside.
