### ISSUE TITLE
hypothesis testing error - ```contrasts can be applied only to factors with 2 or more levels```

### ISSUE THREAD

**Issue by cathalgking** [mildpiggy/DEP2#11]
I am getting an error when running ```test_diff``` as shown below. The error seems to be related to the factors that are in my SE object.

```{r}
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```
My SE object contains the below structure and slots. Is there something I can change with my data here? @mildpiggy 

```{r}
Formal class 'DFrame' [package "S4Vectors"] with 6 slots
  ..@ rownames       : chr [1:78] "patient_1" "patient_2" "patient_3" "patient_4" ...
  ..@ nrows          : int 78
  ..@ elementType    : chr "ANY"
  ..@ elementMetadata: NULL
  ..@ metadata       : list()
  ..@ listData       :List of 11
  .. ..$ label       : chr [1:78] "X1900163018" "X1900163021" "X1900163024" "X1900163027" ...
  .. ..$ ID          : chr [1:78] "patient_1" "patient_2" "patient_3" "patient_4" ...
  .. ..$ condition   : chr [1:78] "patient" "patient" "patient" "patient" ...
  .. ..$ replicate   : int [1:78] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ plate       : int [1:78] 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ Cohort      : int [1:78] 2 2 1 2 0 0 1 2 1 2 ...
  .. ..$ Status_at_dx: int [1:78] 2 2 1 3 0 0 1 3 1 3 ...
  .. ..$ caseset     : int [1:78] 20 20 19 19 19 19 19 19 18 18 ...
  .. ..$ ordn        : int [1:78] 2 1 1 1 2 1 2 2 2 1 ...
  .. ..$ sex         : int [1:78] 2 2 2 2 2 2 2 2 2 2 ...
  .. ..$ age_sampling: num [1:78] 62.6 60.8 60 60.3 60.7 ...
```

Thanks

**Comment by cathalgking** [comment]
I have tried changing that column of the SummarizedExperiment object to a factor with ```as.factor``` but I still have not had any luck with this.
```{r}
plate1_imp_MinProb$condition <- as.factor(plate1_imp_MinProb$condition)
```
In fact, that column did not change from a chr to a factor at all when I did that.
Can you suggest a way to get past this? @mildpiggy 
Thank you!

**Comment by mildpiggy** [comment]
This error should not be caused by the class of the `condition` variable. Can you confirm the value (not class) of `condition` in coldata?`table(colData(plate1_imp_MinProb)$condtion)` or `table(plate1_imp_MinProb$condition)`.
And could you provide the specific parameters used for executing the `test_diff`? @cathalgking

**Comment by cathalgking** [comment]
The parameters I am running for ```test_diff``` are:
```{r}
data_diff <- test_diff(plate1_imp_MinProb, type = "control", control = "patient")
```
The value of condition is shown below.
```{r}
> table(colData(plate1_imp_MinProb)$condtion)
< table of extent 0 >
> table(plate1_imp_MinProb$condition)

patient 
     78
```
Can you suggest what I can change here? I just want to get to a PCA plot?
Thanks @mildpiggy

**Comment by cathalgking** [comment]
I have a few columns in my ```colData``` slot of my SE object that I would like to plot a PCA plot based on for example cohort, age_sampling, sex etc as shown below. Does the ```condition``` column also have to be used for this type of plot? @mildpiggy

**Comment by mildpiggy** [comment]
> The parameters I am running for `test_diff` are:
> 
> ```
> data_diff <- test_diff(plate1_imp_MinProb, type = "control", control = "patient")
> ```
> 
> The value of condition is shown below.
> 
> ```
> > table(colData(plate1_imp_MinProb)$condtion)
> < table of extent 0 >
> > table(plate1_imp_MinProb$condition)
> 
> patient 
>      78
> ```
> 
> Can you suggest what I can change here? I just want to get to a PCA plot? Thanks @mildpiggy

The SE only has one condition "patient", all 78 samples are "patient". Thus `test_diff` can not construst any contrast (compare two condition).

**Comment by mildpiggy** [comment]
> PCA

You can change `indicate` argument in plot_pca, plot_umap, and plot_tsne.

**Comment by mildpiggy** [comment]
> I have other columns in my `colData` slot of my SE object that I would like to plot a PCA plot based on for example cohort, age_sampling, sex etc as shown below. Does the `condition` column also have to be used for this type of plot? Or is there a way to use `test_diff` only on those columns? @mildpiggy
> 
> <img alt="Screenshot 2024-06-24 at 4 06 47 PM" width="755" src="https://private-user-images.githubusercontent.com/32261323/342228245-8049ae5f-7240-4464-a5f1-d6063d6cf7aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODI0NTAsIm5iZiI6MTcxOTI4MjE1MCwicGF0aCI6Ii8zMjI2MTMyMy8zNDIyMjgyNDUtODA0OWFlNWYtNzI0MC00NDY0LWE1ZjEtZDYwNjNkNmNmN2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAyMjIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NzA4ZTJkNjgwNGM3ZTBkOWQ2MjBmYTYwNzI1ODYyN2UwZTYzZTViNDJhNjIyZmU3YzgyZDkxYjhmMTRmMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cke8s6hrbojEpR_ZLIRCBZuWAf-qVjTrr4tSxH9xbuQ">

You can change indicate argument in plot_pca, plot_umap, and plot_tsne.
