### ISSUE TITLE
len_limit not found

### ISSUE THREAD

**Issue by offbrandcereal1** [mildpiggy/DEP2#12]
When using the reshape module in the shiny app to reshape DIA-NN output report.tsv, and using the file.name column as the "sample column", the error is returned "len_limit not found".

This appears to be fixed by editing lines 554-555 of Reshape_module.R, changing len_limit to length_lim.

**Comment by mildpiggy** [comment]
Thank you very much for pointing out the mistake @offbrandcereal1 . I have corrected it in the update.
