### ISSUE TITLE
DEP2::plot_pca() only plots a maximum of 6 replicates

### ISSUE THREAD

**Issue by 1Moe** [mildpiggy/DEP2#13]
Hi, 
DEP2::plot_pca(indicate = c("condition", "replicate")) only plots a maximum of 6 replicates. This seems to be due to only 6 symbols being chosen as indicators. 

Please update if possible to plot all replicates.

best wishes and thanks!

**Comment by mildpiggy** [comment]
Hi. By default, geom_point can map up to 6 distinct variables for shape. Now I have updated plot_pca/Tsne/umap to allow them to map shapes to more than 6 factors. However, having too many shapes on plot is inevitably difficult to distinguish, so I believe that when there are too many "repetitions," it may be preferable to not indicate shapes in the plot.
