### ISSUE TITLE
`filter_se` parameter `fraction` can be misleading.

### ISSUE THREAD

**Issue by m-pauper** [mildpiggy/DEP2#21]
Hello, thanks for publishing DEP and DEP2. 

I just wanted to give some feedback on `filter_se`'s parameter `fraction` as I find it a bit misleading. The description says:

"A numeric from 0 to 1, threshold of missing occupancy of each row"

However, setting the threshold at e.g. 0.4, means that a feature can have 60% missing values. I would expect it to mean that 40% missing values is the maximum threshold allowed.

**Comment by mildpiggy** [comment]
Hi. As you found, my parameter description is not accurate. The `fraction` should be the valid quantitative fraction (1 - missing ratio). In fact, a larger `fraction` corresponds to a stricter filtering. Thank you for your observation, and I will modify the description of parameter `fraction` in future updates.

**Comment by m-pauper** [comment]
Thanks for the quick reaction!
