### ISSUE TITLE
```impute()``` with zero values

### ISSUE THREAD

**Issue by cathalgking** [mildpiggy/DEP2#7]
I would like to just replace any missing values with 0 when using the impute() function. Can this be done with the below code? The function reference page does not specify this.

```{r}
imputed_MLE <- impute(norm, fun = "zero")
```

**Comment by mildpiggy** [comment]
Yes. You can specify the `DEP2::impute` to avoid the to avoid confusion of functions with the same name (could from other packages).
```
imputed_zero <- DEP2::impute(norm, fun = "zero")
```

**Comment by cathalgking** [comment]
Hi @mildpiggy 
That makes sense thanks.
Just to confirm, DEP2 cannot correct for batch effects in proteomics data? I have 6 plates that I would like to correct for technical effects if any. Can you recommend a package that can do this?

**Comment by mildpiggy** [comment]
@cathalgking DEP2 cannot correct the batch effects cross experiments. You can try other tools for this job. Maybe you can begin from statTarget as i said https://github.com/mildpiggy/DEP2/issues/4#issuecomment-2063578307.  However, as far as I can remember, this tool requires an old version of R.
