### ISSUE TITLE
check_enrichment_depends() error！

### ISSUE THREAD

**Issue by lwlive** [mildpiggy/DEP2#9]
Hi, Could you please offer some help?
When I use check_enrichment_depends(), it prompts me to install clusterProfiler, but I have already installed clusterProfiler version 4.10.1. How can I resolve this issue?
![image](https://github.com/mildpiggy/DEP2/assets/29721547/f7fbbd81-0fdc-4f19-9747-e7a72e5e4101)

**Comment by lwlive** [comment]
It seems that I have to use clusterProfiler version 4.3.1.900?
![image](https://github.com/mildpiggy/DEP2/assets/29721547/107f2a96-1deb-43c6-b800-f38ed51e2c83)

**Comment by mildpiggy** [comment]
> It seems that I have to use clusterProfiler version 4.3.1.900? ![image](https://private-user-images.githubusercontent.com/29721547/337059523-107f2a96-1deb-43c6-b800-f38ed51e2c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTcwNjUsIm5iZiI6MTcxNzY1Njc2NSwicGF0aCI6Ii8yOTcyMTU0Ny8zMzcwNTk1MjMtMTA3ZjJhOTYtMWRlYi00M2M2LWI4MDAtZjM4ZWQ1MWUyYzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA2NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZjFhY2RiMDgyNWE3MjZlZjhkYjIwODUxZjkyNTA1YTEzYWQxYjhmMTgzMmE5ZTEzNGE5NzU4MmIwMzBiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rp2EAv1NKr95cLd_lcb8wIdlk_KO9sHF7_MyWXSS9qE)

4.3.1.900 is the minimum version, DEP2 just requires clusterProfiler higher than 4.3.1.900. check_enrichment_depends functions still works in my session. Could you try again after restart R, and could you library clusterProfiler directly? 
![Uploading 1.png…]()

**Comment by mildpiggy** [comment]
> It seems that I have to use clusterProfiler version 4.3.1.900? ![image](https://private-user-images.githubusercontent.com/29721547/337059523-107f2a96-1deb-43c6-b800-f38ed51e2c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTcwNjUsIm5iZiI6MTcxNzY1Njc2NSwicGF0aCI6Ii8yOTcyMTU0Ny8zMzcwNTk1MjMtMTA3ZjJhOTYtMWRlYi00M2M2LWI4MDAtZjM4ZWQ1MWUyYzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA2NTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZjFhY2RiMDgyNWE3MjZlZjhkYjIwODUxZjkyNTA1YTEzYWQxYjhmMTgzMmE5ZTEzNGE5NzU4MmIwMzBiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rp2EAv1NKr95cLd_lcb8wIdlk_KO9sHF7_MyWXSS9qE)

4.3.1.900 is the minimum version, DEP2 just requires clusterProfiler higher than 4.3.1.900. check_enrichment_depends functions still works in my session. Could you try again after restart R, and could you library clusterProfiler directly? 

![1](https://github.com/mildpiggy/DEP2/assets/37103678/f4a1d3dd-e161-46e4-afb1-74e297729991)
